# Define stages for the pipeline
stages:
  - build
  - test
  - package
  - acceptance-test

# Job for building the project
build:
  stage: build
  image: maven:3.8.6-openjdk-11  # Use an appropriate Maven image
  script:
    - mvn clean compile

# Job for running unit tests
unit-test:
  stage: test
  image: maven:3.8.6-openjdk-11  # Use an appropriate Maven image
  script:
    - mvn test

# Job for packaging the application
package:
  stage: package
  image: maven:3.8.6-openjdk-11  # Use an appropriate Maven image
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar  # Adjust path if necessary to where your artifacts are stored

# Job for running acceptance tests
acceptance-test:
  stage: acceptance-test
  image: maven:3.8.6-openjdk-11  # Use an appropriate Maven image
  script:
    - mvn verify  # Or any other command to run your acceptance tests
