# Use an OpenJDK image
#image: openjdk:21-jdk
image: maven:latest


# Define stages for the pipeline
stages:
  - clean
  - compile
  - package
  - start_server
  - test


# Job to clean the project
clean:
  stage: clean
  script:
    - make clean

# Job to compile the project
compile:
  stage: compile
  script:
    - make clean


package:
  stage: package
  script:
    - make package
# Job to start the server
start_server:
  stage: start_server
  script:
    - make server


# Job to run tests
test:
  stage: test
  script:
    - make test

