# Define the image to use for the CI/CD pipeline
image: maven:3.8.5-openjdk-11

# Define stages for the pipeline
stages:

  - compile
  - test
  - package



# Job to compile the project
compile:
  stage: compile
  script:
    - mvn compile


# Job to start the server
start_server:
  stage: test
  script:
    - java -jar libs/reference-server-0.1.0.jar &
    - sleep 5

# Job to run tests
test:
  stage: test
  script:
    - mvn test -e
    - mvn package
  dependencies:
    - start_server

# Job to build the project
package:
  stage: package
  script:
    - mvn package
  dependencies:
    - compile

