# Use Eclipse Temurin JDK 21 image for CI/CD jobs
image: eclipse-temurin:21-jdk

# Define pipeline stages
stages:
  - build
  - test
  - package
  - publish

# Define Maven options
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
  DOCKER_REGISTRY: registry.gitlab.wethinkco.de
  IMAGE_NAME: $DOCKER_REGISTRY/nsilima023b/cjc1_brownfields_2024
  TAG: latest

# Cache Maven dependencies
cache:
  paths:
    - .m2/repository

# Before script to set up environment
before_script:
  - apt-get update && apt-get install -y maven
  - export JAVA_HOME="/opt/java/openjdk"
  - echo "Using Java version:"
  - java -version
  - mvn --version

# Build stage
build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
  timeout: 30m

# Test stage
test:
  stage: test
  script:
    - java -jar libs/reference-server-0.1.0.jar &
    - sleep 5
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

# Package stage
package:
  stage: package
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week


# Publish Docker image stage
publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$TAG .
    - docker push $IMAGE_NAME:$TAG
