# Define stages for the pipeline
stages:
  - build
  - test
  - package
  - acceptance-test

# Jobs for each stage
compile:
  stage: build
  script:
    - make  # Runs the default target in your Makefile

unit-test:
  stage: test
  script:
    - make test  # Replace with the specific Makefile target for unit tests

package:
  stage: package
  script:
    - make package  # Replace with the specific Makefile target for packaging

acceptance-test:
  stage: acceptance-test
  script:
    - make start-server &  # Start your server using a Makefile target
    - sleep 5  # Wait for the server to start
    - make acceptance-test  # Run acceptance tests using a Makefile target
    - make stop-server  # Optionally stop the server if needed
