# Use an OpenJDK image
#image: openjdk:21-jdk
image: maven:latest
services:
  - docker:dind

# Define stages for the pipeline
stages:
  - clean
  - compile
  - package
  - start_server
  - test


# Job to clean the project
clean:
  stage: clean
  script:
    - mvn clean

# Job to compile the project
compile:
  stage: compile
  script:
    - mvn compile


package:
  stage: package
  script:
    - mvn package
# Job to start the server
start_server:
  stage: start_server
  script:
    - java -jar target/toyrobot-1.0-SNAPSHOT-jar-with-dependencies.jar
    - sleep 5


# Job to run tests
test:
  stage: test
  script:
    - mvn test

