image: eclipse-temurin:21-jdk

stages:
  - build
  - test
  - package

variables:

  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"

before_script:
  - apt-get update && apt-get install -y maven
  - export JAVA_HOME="/opt/java/openjdk"
  - echo "Using Java version:"
  - java -version
  - mvn --version

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - java -jar libs/reference-server-0.1.0.jar
    - sleep 5
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

package:
  stage: package
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  timeout: 30m