# Use Eclipse Temurin JDK 21 image for CI/CD jobs
image: eclipse-temurin:21-jdk

# Define pipeline stages
stages:
  - build
  - test
  - package
  - publish

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
  DOCKER_REGISTRY: gitlab.wethinkco.de
  IMAGE_NAME: nsilima023b/cjc1_brownfields_2024
  TAG: latest

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update && apt-get install -y maven
  - export JAVA_HOME="/opt/java/openjdk"
  - echo "Using Java version:"
  - java -version


build:
  stage: build
  timeout: 30m
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/


test:
  timeout: 30m
  stage: test

  script:
    - java -jar libs/reference-server-0.1.0.jar &
#    - SERVER_PID=$!
    - sleep 5
    - mvn test
#    - kill $SERVER_PID
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

package:
  timeout: 30m
  stage: package

  script:
    - mvn package
#    - java -jar target/toyrobot-1.0-SNAPSHOT-jar-with-dependencies.jar
#    - sleep 5
#    - mvn test
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

publish:
  timeout: 60m
  stage: publish

  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker pull eclipse-temurin:21-jdk
    - docker login gitlab.wethinkco.de:5050 -u "$CI_REGISTRY_USER2" -p "CI_REGISTRY_PASSWORD2"
  script:
    - docker build -t $IMAGE_NAME:$TAG .
    - docker push $IMAGE_NAME:$TAG
