stages:
  - build
  - test
  - deploy  

build-test-job:  # Combined build and test jobs
  stage: build
  image: maven:latest
  script:
    - echo "Compiling the code and running unit tests..."
    - mvn clean install -Dreference.server.url=$REFERENCE_SERVER_URL

deploy-job:  # Added deploy job
  stage: deploy
  image: # Define image based on deployment method
  script:
    - echo "Deploying the application..."
    # Add deployment commands here
  # Add error handling here (optional)

