stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: maven:latest  # Use maven:latest image
  script:
    - echo "Compiling the code..."
    - mvn clean compile

unit-test-job:
  stage: test
  image: maven:latest  # Use maven:latest image
  script:
    - echo "Starting reference server..."
    - java -jar libs/reference-server-0.1.0.jar &  # Start reference server in background
    - export REFERENCE_SERVER_URL=http://localhost:8080  # Set reference server URL (replace port if needed)
    - echo "Running unit tests against reference server..."
    - mvn test  # Run tests using Maven


