# Define stages for the pipeline
stages:
  - build
  - test
  - package
  - acceptance-test

# Jobs for each stage
compile:
  stage: build
  script:
    - make compile  # Replace with the appropriate Makefile target

unit-test:
  stage: test
  script:
    - make test  # Replace with the appropriate Makefile target

package:
  stage: package
  script:
    - make package  # Replace with the appropriate Makefile target
  artifacts:
    paths:
      - path/to/your/artifacts  # Adjust this path to where your artifacts are stored

acceptance-test:
  stage: acceptance-test
  script:
    - make start-server &  # Start your server using a Makefile target
    - sleep 5  # Wait for the server to start
    - make acceptance-test  # Run acceptance tests using a Makefile target
    - make stop-server  
