# Define stages for the pipeline
stages:
  - build
  - test
  - package
  - acceptance-test

# Jobs for each stage
compile:
  stage: build
  script:
    - mvn clean compile


acceptance-test:
  stage: acceptance-test
  script:
    - java -jar libs/reference-server-0.1.0.jar &  # Start your server
    - sleep 5  # Wait for server to start
    - mvn verify  # Run acceptance tests against the server
    - # Stop the server here if needed

unit-test:
  stage: test
  script:
    - mvn test


package-server:
  stage: package
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

release:
  stage: package
  script:
    - mvn clean package -P release  # Example: profile for release build
  artifacts:
    paths:
      - target/*.jar
