# Use an OpenJDK image
image: openjdk:21-jdk

services:
  - docker:dind

variables:
  MAVEN_VERSION: 3.8.6

before_script:
  # Install Maven
  - apt-get update
  - apt-get install -y wget tar
  - wget https://apache.mirrors.lucidnetworks.net/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  - tar xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz
  - mv apache-maven-${MAVEN_VERSION} /opt/maven
  - ln -s /opt/maven/bin/mvn /usr/bin/mvn
  - mvn --version  # Verify Maven installation

# Define stages for the pipeline
stages:
  - clean
  - compile
  - test
  - package

# Job to clean the project
clean:
  stage: clean
  script:
    - mvn --version

# Job to compile the project
compile:
  stage: compile
  script:
    - mvn --version
#  dependencies:
#    - clean

# Job to start the server
start_server:
  stage: test
  script:
    - java -jar libs/reference-server-0.1.0.jar &
    - sleep 5

# Job to run tests
test:
  stage: test
  script:
    - mvn --version
    - mvn --version
#  dependencies:
#    - start_server

# Job to build the project
package:
  stage: package
  script:
    - mvn --version
#  dependencies:
#    - compile
