TARGET = MyProgram

Clean:
	@mvn clean
Compile:clean
	@mvn compile&


Build:compile
	@mvn package 

server:
	@java -jar libs/reference-server-0.1.0.jar &
	sleep 10
	
 

test:server &
	@mvn test


.DEFAULT_GOAL := build



